# Generated by Django 2.2 on 2022-06-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('caldata', models.FloatField()),
            ],
            options={
                'db_table': 'tb_one',
            },
        ),
        migrations.CreateModel(
            name='Cal02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('caldata', models.FloatField()),
            ],
            options={
                'db_table': 'tb_two',
            },
        ),
        migrations.CreateModel(
            name='Cal03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('caldata', models.FloatField()),
            ],
            options={
                'db_table': 'tb_three',
            },
        ),
        migrations.CreateModel(
            name='Calhim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('diff', models.FloatField()),
                ('global_irr', models.FloatField()),
                ('direct', models.FloatField()),
                ('dg_radio', models.FloatField()),
            ],
            options={
                'db_table': 'tb_him',
            },
        ),
        migrations.CreateModel(
            name='Psrv1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nm_340', models.IntegerField()),
                ('nm_380', models.IntegerField()),
                ('nm_440', models.IntegerField()),
                ('nm_500', models.IntegerField()),
                ('nm_675', models.IntegerField()),
                ('nm_870', models.IntegerField()),
                ('nm_937', models.IntegerField()),
                ('nm_1020', models.IntegerField()),
                ('nm_1640', models.IntegerField()),
                ('wktemp', models.FloatField()),
                ('envitemp', models.FloatField()),
                ('envihumi', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('Inenvitemp', models.FloatField()),
                ('Inenvihumi', models.FloatField()),
                ('Headtemp', models.FloatField()),
                ('Headhumi', models.FloatField()),
                ('FQ1', models.IntegerField()),
                ('FQ2', models.IntegerField()),
                ('FQ3', models.IntegerField()),
                ('FQ4', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_psrv1',
            },
        ),
        migrations.CreateModel(
            name='Spec01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('reflectance', models.FloatField()),
            ],
            options={
                'db_table': 'tb_spec01',
            },
        ),
        migrations.CreateModel(
            name='Spec02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('reflectance', models.FloatField()),
            ],
            options={
                'db_table': 'tb_spec02',
            },
        ),
        migrations.CreateModel(
            name='Spec03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wavelength', models.IntegerField()),
                ('reflectance', models.FloatField()),
            ],
            options={
                'db_table': 'tb_spec03',
            },
        ),
    ]
