# Generated by Django 2.2 on 2022-06-20 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('wavelength', models.IntegerField()),
                ('caldata', models.FloatField()),
            ],
            options={
                'db_table': 'tb_one',
            },
        ),
        migrations.CreateModel(
            name='Cal02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('wavelength', models.IntegerField()),
                ('caldata', models.FloatField()),
            ],
            options={
                'db_table': 'tb_two',
            },
        ),
        migrations.CreateModel(
            name='Cal03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('wavelength', models.IntegerField()),
                ('caldata', models.FloatField()),
            ],
            options={
                'db_table': 'tb_three',
            },
        ),
        migrations.CreateModel(
            name='Calhim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('wavelength', models.IntegerField()),
                ('diff', models.FloatField()),
                ('global_irr', models.FloatField()),
                ('direct', models.FloatField()),
                ('dg_radio', models.FloatField()),
            ],
            options={
                'db_table': 'tb_him',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
