# Generated by Django 2.2 on 2022-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psrv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('wZenith', models.FloatField()),
                ('wAirmass', models.FloatField()),
                ('wCloud', models.IntegerField()),
                ('wAOD340', models.FloatField()),
                ('wAOD380', models.FloatField()),
                ('wAOD440', models.FloatField()),
                ('wAOD500', models.FloatField()),
                ('wAOD675', models.FloatField()),
                ('wAOD870', models.FloatField()),
                ('wAOD1020', models.FloatField()),
                ('wAOD1640', models.FloatField()),
                ('walpha', models.FloatField()),
                ('wbeta', models.FloatField()),
                ('wAOD550', models.FloatField()),
                ('wPW', models.FloatField()),
            ],
            options={
                'db_table': 'tb_psrv2',
            },
        ),
    ]
